config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: :callbacks, registrations: "registrations" }
  root "games#index"

  resources :users
  resources :games do
    resources :critics
  end
  resources :companies do
    resources :critics
  end

  resources :critics
  post "/add_platform", to: "games#add_platform"
  delete "/delete_platform", to: "games#delete_platform"
  post "/add_genre", to: "games#add_genre"
  delete "/delete_genre", to: "games#delete_genre"

  post "/add_developer", to: "involved_companies#add_developer"
  delete "/remove_developer", to: "involved_companies#remove_developer"
  post "/add_publisher", to: "involved_companies#add_publisher"
  delete "/remove_publisher", to: "involved_companies#remove_publisher"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/game.rb
class Game < ApplicationRecord
  # Validations
  validates :name, uniqueness: true, presence: true
  validates :release_date, allow_blank: true, comparison: { less_than: Time.zone.now }
  validates :rating, allow_blank: true,
                     numericality: { in: 0..100, message: "Should be between 0 and 100" }
  validate :parent, :child
  # validate :valid_rating

  # Associations
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  belongs_to :parent, class_name: "Game", optional: true
  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies
  has_many :critics, as: :criticable, dependent: :destroy
  has_many :expansions, class_name: "Game", foreign_key: "parent_id",
                        dependent: :destroy, inverse_of: "parent"
  enum category: { main_game: 0, expansion: 1 }
  has_one_attached :cover

  has_many :received_critics, class_name: "Critic", as: :criticable, dependent: :destroy

  private

  def parent
    return unless category == "main_game" && !parent_id.nil?

    errors.add(:parent_id, "must be blank. Select no parent game")
  end

  def child
    return unless category == "expansion" && parent_id.nil?

    errors.add(:parent_id, "must not be blank. Select parent game")
  end

  # def valid_rating
  #   return if !rating.nil? && rating.between?(0, 100)

  #   errors.add(:rating, "Should be between 0 and 100")
  # end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game,
                only: %i[show edit update destroy add_platform add_genre delete_platform
                         delete_genre]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
    authorize @game
    all_critics = policy_scope(Critic)
    received_critics = @game.received_critics
    @game_critics = all_critics & received_critics
  end

  # GET /games/new
  def new
    @game = Game.new
    authorize @game
  end

  # GET /games/1/edit
  def edit
    authorize @game
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    authorize @game

    if @game.save
      redirect_to root_path, notice: "Game was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /games/1
  def update
    authorize @game
    if @game.update(game_params)
      redirect_to root_path, notice: "Game was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def add_platform
    authorize @game, :update?
    @platform = Platform.find(params[:platform_id])
    # authorize @platform #################################
    @game.platforms << @platform
    redirect_to game_path(@game)
  end

  def delete_platform
    authorize @game, :update?
    @platform = Platform.find(params[:platform_id])
    # authorize @platform
    @game.platforms.delete(@platform)
    redirect_to game_path(@game), status: :see_other
  end

  def add_genre
    authorize @game, :update?
    @genre = Genre.find(params[:genre_id])
    # authorize @genre
    @game.genres << @genre
    redirect_to game_path(@game)
  end

  def delete_genre
    authorize @game, :update?
    @genre = Genre.find(params[:genre_id])
    # authorize @genre
    @game.genres.delete(@genre)
    redirect_to game_path(@game), status: :see_other
  end

  # DELETE /games/1
  def destroy
    authorize @game
    @game.destroy
    redirect_to games_url, notice: "Game was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :summary, :release_date, :category, :rating, :parent_id,
                                 :cover)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, class: "form") do |form| %>
  <% if game.errors.any? %>
    <div class = "errors">
      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <h1 class="heading"><%= form_type %> game</h1> 
  <div>
    <%= form.label :name, class: "form__label overline block" %>
    <%= form.text_field :name, class: "form__input", placeholder: "Secret planning" %>
  </div>

  <div>
    <%= form.label :summary, class: "form__label overline block" %>
    <%= form.text_area :summary, class: "form__input form__input--text-area", placeholder: "This is the best department yet..." %>
  </div>

  <div>
    <%= form.label :release_date, class: "form__label overline block" %>
    <%= form.date_field :release_date, class: "form__input" %>
  </div>

  <div>
    <%= form.label :rating, class: "form__label overline block" %>
    <%= form.number_field :rating, step: "0.1", placeholder: "0.0", class: "form__input" %>
  </div>

  <div>
    <%= form.label :category, class: "form__label overline block" %>
    <%= form.select :category, Game.categories.keys.map { |key| [key.humanize.titleize, key] },{}, {class: "form__input form__input--select"}   %>
  </div>

  <div>
    <%= form.label :parent_id, class: "form__label overline block" %>
    <%= form.collection_select :parent_id, Game.where("parent_id is null"), :id, :name,{include_blank: "No parent"}, {class: "form__input form__input--select"} %>
  </div>
  <%# VALIDAR ESCOGER CORRECTAMENTE CATEGORY Y PARENT %>
  
  <div>
    <%= form.label :cover, class: "form__label overline block" %>
    <%= form.file_field :cover %>
  </div>

  <div class="form__control">
    <%= form.submit form_type == 'New' ? 'Create game' : 'Update game', class: "button button--primary form__input form__input--submit" %>
    <%= link_to "Back", games_path, class: "form__input form__input--back" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">

  <div class="element__container">
    <div>
      <p class="content-xs center-text"><%= game.summary %></p>
    </div>

    <div>
      <p class="content-sm">Genres: </p>
      <div class="element__attribute-list">
        <% game.genres.each do |genre| %>
          <div class="element__attribute-button">
            <span class="content-xs regular"><%= genre.name %></span>
            <% if policy(Game).update? %>
              <%= link_to  image_tag("cross-delete-icon.png"), delete_genre_path(genre_id: genre, id: game), data: {turbo_method: :delete}  %> 
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div>
      <p class="content-sm">Platforms: </p>
      <div class="element__attribute-list">
        <% game.platforms.each do |platform| %>
          <div class="element__attribute-button">
            <span class="content-xs regular"><%= platform.name %></span>
            <% if policy(Game).update? %>
              <%= link_to  image_tag("cross-delete-icon.png"), delete_platform_path(platform_id: platform, id: game), data: {turbo_method: :delete}  %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <div>
      <p class="content-sm">Developers: </p>
      <div class="element__attribute-list">
        <% game.involved_companies.where(developer: true).each do |ic| %>
          <div class="element__attribute-button">
            <span class="content-xs regular"><%= ic.company.name %></span>
            <%if policy(Game).update?%>
              <%= link_to  image_tag("cross-delete-icon.png"), remove_developer_path(ic_id: ic, id: game), data: {turbo_method: :delete} %>
            <%end%>
          </div>
        <% end %>
      </div>
    </div>

    <div>
      <p class="content-sm">Publishers: </p>
      <div class="element__attribute-list">
      <% game.involved_companies.where(publisher: true).each do |ic| %>
        <div class="element__attribute-button">
          <span class="content-xs regular"><%= ic.company.name %></span>
          <%if policy(Game).update?%>
            <%= link_to  image_tag("cross-delete-icon.png"), remove_publisher_path(ic_id: ic, id: game), data: {turbo_method: :delete} %>
          <%end%>
        </div>
      <% end %>
      </div>
    </div>

    <%if policy(Game).update?%>
      <p class="heading--xs regular">Add Relations:</p>

      <div>
        <%= form_with(url: add_genre_path(id: @game), class: "select element__select") do |f| %> 
          <%= f.collection_select :genre_id, Genre.all - @game.genres, :id, :name, options = {prompt: "Select Genre"}, html_options = {class: "element__select-type"}%>
          <%= f.submit "Add Genre", class: "button button--primary button--sm"%>
        <% end %>
      </div>

      <div>
        <%= form_with(url: add_platform_path(id: @game), class: "select element__select") do |f| %>
          <%= f.collection_select :platform_id, Platform.all - @game.platforms, :id, :name, options = {prompt: 'Select Platform'}, html_options = {class: "element__select-type"} %>
          <%= f.submit "Add Platform", class: "button button--primary button--sm" %>
        <% end %>
      </div>

      <div>
        <%= form_with(url: add_developer_path(id: @game), class: "select element__select") do |f| %>
        <%= f.collection_select :company_id,
                                Company.order(:name) - @game.involved_companies.where(developer: true).map { |ic| ic.company},
                                :id, :name, options = {prompt: "Select Company"}, html_options = {class: "element__select-type"}%>
        <%= f.submit "Add developer", class: "button button--primary button--sm"  %>
        <% end %>
      </div>

      <div>
        <%= form_with(url: add_publisher_path(id: @game), class: "select element__select") do |f| %>
        <%= f.collection_select :company_id,
                                Company.order(:name) - @game.involved_companies.where(publisher: true).map { |ic| ic.company},
                                :id, :name, options = {prompt: "Select Company"}, html_options = {class: "element__select-type"}%>
        <%= f.submit "Add publisher", class: "button button--primary button--sm"  %>
        <% end %>
      </div>
    <%end%>
  </div>

</div>

app/views/games/_game_card.html.erb
<div class="element-card gap-1">
    <div class="element-cover-container">
    <%if game.cover.attached? %>
    <%= link_to image_tag(game.cover, alt: "element-image", class: "element-image"), game %> 
    <% else %>
      <%= image_tag("game-default.jpg", alt: "element-image", class: "element-image") %> 
    <% end %>
    </div>

  <div class="flex flex-column space-between font-primary">
    <div class="flex space-between">
      <div>
        <div class= "content-lg regular"><%= link_to game.name, game %></div>
        <div class="flex gap-0-25">
          <% if game.release_date %>
            <p class= "content-xs"><%= game.release_date.year %></p>
          <% end %>
          <div class= "x-small">· <%= (policy_scope(Critic) & game.received_critics).size %> Critics</div>
        </div>
      </div>
      <div>
        <div class="button button--rating gap-0-25"><%= image_tag("star-icon.png", alt: "star-icon", class: "ele") %><%= game.rating %></div>
      </div>
    </div>

    <p class= "element-description"><%= game.summary %></p>

    <div class="flex">
      <div class="element-icons">
        <% if policy(Game).update? %>
          <%= link_to "Edit", edit_game_path(game), class: 'button button--sm button--primary display-initial'%>
        <% end %>
        <% if policy(Game).destroy? %>
          <%= link_to "Delete", game, data: { turbo_method: :delete }, class: 'button button--sm button--primary display-initial' %>
        <% end %>
      </div>
    </div>
  </div>


</div>

app/views/games/edit.html.erb
<div class="section">
<%= render "form", game: @game, form_type: "Edit" %>
</div>

<br>

app/views/games/index.html.erb
<section class="">
  <div class="flex space-between flex-end my-1">
    <div class="heading--sm text-center mt-1"><h2>Games</h2></div>
    
    <% if policy(Game).new? %>
    <div class="text-center">
      <%= link_to "NEW GAME", new_game_path, class:"button button--sm button--primary display-initial" %>
    </div>
    <% end %>
  </div>

  <div id="games" class="elements__cards_container">
    <% @games.order(:name).each do |game| %>
      <%= render "games/game_card", game: game %>
    <% end %>
  </div>

</section>

app/views/games/new.html.erb
<div class="container-lg section">



  <%= render "form", game: @game, form_type: "New" %>
</div>

<br>

app/views/games/show.html.erb
<section class="p-1 element__container ">

  <div class="element__showcase">
    <div>
      <%if @game.cover.attached? %>
        <%= image_tag(@game.cover, alt: "Cover image game", class: "element__showcase-image") %>
      <% else %>
        <%= image_tag("game-default.jpg", alt: "Cover game default", class: "element__showcase-image") %>   
      <% end %>
    </div>

    <div class="element__showcase-info">
      <div>
        <h2 class="heading--sm regular"><%= @game.name %></h2>
        <p class="content-xs regular"><%= @game.release_date.year %></p>
      </div>
      <div class="button button--secondary p-0-5">
        <p class="content-xl font-family-inter"><%= @game.rating %></p>
      </div>
    </div>
  </div>

  <div>
    <ul class="element__showcase-links">
      <li><a href="#element_details"><p class="gray-400">Game Details</p></a></li>
      <li><a href="#element_critics"><p class="gray-400">Critics (<%= @game_critics.size %>)</p></a></li>
    </ul>
  </div>

  <div class="element__show-body">
    <div class="element_details" id="element_details">
      <%= render @game %>
    </div>


    <div class="element_critics element__container" id="element_critics">
      <%= render "critics/form", {critic: Critic.new, criticable: @game }  %>
      <% @game_critics.sort_by { |c| c.created_at }.reverse.each do |critic| %>
        <div>
          <hr>
          <h3><%=critic.title%></h3>
          <p class="content-sm gray-300">By <%=critic.user.username%></p>
          <p><%=critic.body%></p>
          <div class="critics__options">
            <p class="content-sm gray-300">Sent <%= time_ago_in_words(critic.created_at)%> ago</p>
            <div class="flex flex-center flex-gap-10">  <%# Añadir estilos%>
              <% unless critic.approved%>
                <% if current_user.admin? %>
                  <%= link_to  "Approve", game_critic_path(@game, critic), data: { turbo_method: :patch }, class:"anchor-red"%>
                <% else %>
                  <span class="content-sm gray-300">Pending approval</span>
                <% end %>
              <% end %>
              <% if critic.user == current_user || current_user.admin? %>
                <%= button_to image_tag("trash-icon.png"), critic, method: :delete, class: 'trash__icon'%>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="center-text">
    <%= link_to "Back", games_path, class: "primary-500" %>
  </div>
</section>