config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: :callbacks, registrations: "registrations" }
  root "games#index"

  resources :users
  resources :games do
    resources :critics
  end
  resources :companies do
    resources :critics
  end

  resources :critics
  post "/add_platform", to: "games#add_platform"
  delete "/delete_platform", to: "games#delete_platform"
  post "/add_genre", to: "games#add_genre"
  delete "/delete_genre", to: "games#delete_genre"

  post "/add_developer", to: "involved_companies#add_developer"
  delete "/remove_developer", to: "involved_companies#remove_developer"
  post "/add_publisher", to: "involved_companies#add_publisher"
  delete "/remove_publisher", to: "involved_companies#remove_publisher"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/company.rb
class Company < ApplicationRecord
  # Validations
  validates :name, presence: true, uniqueness: true
  validate :valid_start_date_min, :valid_start_date_max
  has_many :critics, as: :criticable, dependent: :destroy
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies
  has_one_attached :cover

  has_many :received_critics, class_name: "Critic", as: :criticable, dependent: :destroy

  private

  def valid_start_date_min
    return unless !start_date.nil? && start_date > 5.years.ago

    errors.add(:start_date, "Rome was not created in a day")
  end

  def valid_start_date_max
    return unless !start_date.nil? && start_date < 50.years.ago

    errors.add(:start_date, "Too Old")
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: %i[show edit update destroy]

  # GET /companies
  def index
    @companies = Company.all
  end

  # GET /companies/1
  def show
    authorize @company
    all_critics = policy_scope(Critic)
    received_critics = @company.received_critics
    @company_critics = all_critics & received_critics
  end

  # GET /companies/new
  def new
    @company = Company.new
    authorize @company
  end

  # GET /companies/1/edit
  def edit
    authorize @company
  end

  # POST /companies
  def create
    @company = Company.new(company_params)
    authorize @company

    if @company.save
      redirect_to companies_path, notice: "Company was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/1
  def update
    authorize @company
    if @company.update(company_params)
      redirect_to companies_path, notice: "Company was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /companies/1
  def destroy
    authorize @company
    @company.destroy
    redirect_to companies_url, notice: "Company was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country, :cover)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_company.html.erb
<div id="<%= dom_id company %>">

  <div class="element__container">
    <div>
      <p class="content-xs center-text"><%= company.description %></p>
    </div>

    <div>
      <strong>Games: (<%=company.games.size%>)</strong>
      <% company.games.each do |game|%>
        <%= render "games/game_card", game: game %>
      <% end %>
    </div>
  </div>

</div>

app/views/companies/_company_card.html.erb
<div class="container">
  <div class="cover">
    <%if company.cover.attached? %>
    <%= link_to image_tag(company.cover, alt: "Cover image company", class: "img-card"), company %>
  <% else %>
    <%= image_tag("company-default-logo.png", alt: "Cover company default", height: "100px", class: "img-card") %>   
  <% end %>
  </div>

  <div class="company_card card">
    <div>
      <span class= "title"><%= link_to company.name, company, style: "margin: 0" %></span>
      <p class= "year">
      <%= company.start_date.nil? ? "No start date" : company.start_date.year%> -
      <%= company.country.nil? ? "No country" : company.country%>
      </p>
    </div>
    <p class= "company_description"><%= company.description %></p>
    <span class= "x-small"><%= company.games.size %> Games</span>

    <div class="icons">
      <%if policy(Company).update?%>
      <%= link_to image_tag("edit-icon.png"), edit_company_path(company), class: 'edit__icon'%>
      <%end%>
      <%if policy(Company).destroy?%>
      <%= button_to image_tag("trash-icon.png"), company, method: :delete, class: 'trash__icon' %>
      <%end%>
    </div>
  </div>

</div>

app/views/companies/_form.html.erb
<%= form_with(model: company, class: "form") do |form| %>
  <% if company.errors.any? %>
    <div class = "errors">

      <ul>
        <% company.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h1 class="heading form__heading"><%= form_type %> Company</h1>
  <div>
    <%= form.label :name, class: "form__label overline block" %>
    <%= form.text_field :name, class: "form__input", placeholder: "Company SA" %>
  </div>

  <div>
    <%= form.label :description, class: "form__label overline block" %>
    <%= form.text_area :description, class: "form__input form__input--text-area", placeholder: "About the company..." %>
  </div>

  <div>
    <%= form.label :start_date, class: "form__label overline block" %>
    <%= form.date_field :start_date, class: "form__input"  %>
  </div>

  <div>
    <%= form.label :country, class: "form__label overline block" %>
    <%= form.text_field :country, class: "form__input", placeholder: "Somewhere" %>
  </div>

  <div>
    <%=form.label :cover, class: "form__label overline block"%>
    <%= form.file_field :cover%>
  </div>

  <div class="form__control">
    <%= form.submit form_type == 'New' ? 'Create company' : 'Update company', class: "button button--primary form__input form__input--submit" %>
    <%= link_to "Back", companies_path, class: "form__input form__input--back" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div class="section">
<%= render "form", company: @company, form_type: "Edit" %>
</div>

app/views/companies/index.html.erb
<main >
  <div class="text-center mb-2">
      <h2 class="company--title__header">Companies</h2>
      <%if policy(Company).new?%>
        <%= link_to "NEW COMPANY", new_company_path, class:"button--sm button--primary header_button" %>
      <%end%>
  </div>

<div id="companies" class="companies_card">
  <% @companies.order(:name).each do |company| %>
    <%= render "companies/company_card", company: company %>
  <% end %>
</div>

</main>

app/views/companies/new.html.erb
<div class="section">
  <%= render "form", company: @company, form_type: "New" %>
</div>

app/views/companies/show.html.erb
<section class="element__container p-1">

  <div class="element__showcase">
    <div>
      <%if @company.cover.attached? %>
        <%= image_tag(@company.cover, alt: "Cover image company", class: "element__showcase-image") %>
      <% else %>
        <%= image_tag("company-default-logo.png", alt: "Cover company default", height: "100px") %>
      <% end %>
    </div>

    <div>
      <h2 class="heading--sm regular"> <%=@company.name%></h2>
      <p class="content-xs regular"><%= @company.start_date.nil? ? "No start date" : @company.start_date.year%> -
      <%= @company.country.nil? ? "No country" : @company.country%>
      </p>
    </div>
  </div>

  <div>
    <ul class="element__showcase-links">
      <li><a href="#element_details"><p class="gray-400">Company Details</p></a></li>
      <li><a href="#element_critics"><p class="gray-400">Critics (<%= @company_critics.size %>)</p></a></li>
    </ul>
  </div>

  <div class="element__show-body">
    <div class="element_details" id="element_details">
      <%= render @company %>
    </div>

    <div class="element_critics element__container" id="element_critics">
      <%= render "critics/form", {critic: Critic.new, criticable: @company }  %>
      <% @company_critics.sort_by { |c| c.created_at }.reverse.each do |critic| %>
      <div>
        <hr>
        <h3><%=critic.title%></h3>
        <p class="content-sm gray-300">By <%=critic.user.username%></p>
        <p><%=critic.body%></p>
        <div class="critics__options">
          <p>Sent <%= time_ago_in_words(critic.created_at)%> ago</p>
          <div class="flex flex-center flex-gap-10">
            <% unless critic.approved%>
              <% if current_user.admin? %>
                <%= link_to  "Approve", company_critic_path(@company, critic), data: { turbo_method: :patch }, class:"anchor-red"%>
              <% else %>
                <span class="content-sm gray-300">Pending approval</span>
              <% end %>
            <% end %>
            <% if critic.user == current_user || current_user.admin? %>
              <%= button_to image_tag("trash-icon.png"), critic, method: :delete, class: 'trash__icon'%>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

  <div class="center-text">
    <%= link_to "Back", companies_path, class: "primary-500" %>
  </div>

</section>