config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: :callbacks, registrations: "registrations" }
  root "games#index"

  resources :users
  resources :games do
    resources :critics
  end
  resources :companies do
    resources :critics
  end

  resources :critics
  post "/add_platform", to: "games#add_platform"
  delete "/delete_platform", to: "games#delete_platform"
  post "/add_genre", to: "games#add_genre"
  delete "/delete_genre", to: "games#delete_genre"

  post "/add_developer", to: "involved_companies#add_developer"
  delete "/remove_developer", to: "involved_companies#remove_developer"
  post "/add_publisher", to: "involved_companies#add_publisher"
  delete "/remove_publisher", to: "involved_companies#remove_publisher"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriticsRc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# HEADER %>
    <header class="header">
      <div class="container-lg">
        <nav class = "navbar">
          <div class="navbar__main">
            <%= link_to image_tag("icons/logo.svg"), root_path %>
            <figure class="navbar__toogle" onclick="showMenu()">
              <svg class = "menu-icon" width="14" height="12" viewBox="0 0 14 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M0 1C0 0.447715 0.447715 0 1 0H13C13.5523 0 14 0.447715 14 1C14 1.55228 13.5523 2 13 2H1C0.447715 2 0 1.55228 0 1Z" fill="#303036"/>
                <path fill-rule="evenodd" clip-rule="evenodd" d="M0 6C0 5.44772 0.447715 5 1 5H13C13.5523 5 14 5.44772 14 6C14 6.55228 13.5523 7 13 7H1C0.447715 7 0 6.55228 0 6Z" fill="#303036"/>
                <path fill-rule="evenodd" clip-rule="evenodd" d="M0 11C0 10.4477 0.447715 10 1 10H13C13.5523 10 14 10.4477 14 11C14 11.5523 13.5523 12 13 12H1C0.447715 12 0 11.5523 0 11Z" fill="#303036"/>
              </svg>
              <svg class="close-icon" width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M0.292893 0.292893C0.683417 -0.0976311 1.31658 -0.0976311 1.70711 0.292893L6 4.58579L10.2929 0.292893C10.6834 -0.0976311 11.3166 -0.0976311 11.7071 0.292893C12.0976 0.683417 12.0976 1.31658 11.7071 1.70711L7.41421 6L11.7071 10.2929C12.0976 10.6834 12.0976 11.3166 11.7071 11.7071C11.3166 12.0976 10.6834 12.0976 10.2929 11.7071L6 7.41421L1.70711 11.7071C1.31658 12.0976 0.683417 12.0976 0.292893 11.7071C-0.0976311 11.3166 -0.0976311 10.6834 0.292893 10.2929L4.58579 6L0.292893 1.70711C-0.0976311 1.31658 -0.0976311 0.683417 0.292893 0.292893Z" fill="#303036"/>
              </svg>
            </figure>
          </div>
          <% if user_signed_in? %>
            <ul class="navbar__links">
              <li>Welcome <%=current_user.username%></li>
              <li><%= link_to  "Edit profile", edit_user_registration_path, class: "navbar__menu-links" %></li>
              <li><%= link_to  "Games", root_path, class: "navbar__menu-links"  %></li>
              <li><%= link_to  "Companies", companies_path, class: "navbar__menu-links"  %></li>
              <li><%= link_to "LOG OUT", destroy_user_session_path, data: {turbo_method: :delete}, class:"button button--secondary"%></li>
            </ul>
          <% else %>
            <ul class="navbar__links">
              <li>Sign in to start criting games and companies</li>
              <li><%= link_to  "Sign in", new_user_session_path, class: "button button--primary " %></li>
            </ul>
          <% end %>
        </nav>
      </div>
    </header>
    <div class="container-lg section">
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% elsif alert %>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>

      <%# FOOTER %>
      <footer class="footer">
        <div class="footer footer__content">
          <h3 class = "content-sm" >Build with ♥ by</h3>
          <div class="footer--names">
            <div class="footer__member-tag"><%= image_tag("LinkedIn-icon.png", size: "12") %><h3 class = "content-sm">David Montoya</h3></div>
          </div>
          <h3 class = "content-sm" >© 2022 - Critics RC</h3>
          <p class = "content-sm">with <strong>Codeable Org</strong></p>
        </div>
    </div>

  <script>
    function showMenu(){
      /* Show menu*/
      let navBarMobile = document.querySelector(".navbar__links");
      navBarMobile.classList.toggle ("navbar--menu-show");

      /* Remove padding bottom*/
      let paddingBottom = document.querySelector(".navbar");
      paddingBottom.classList.toggle ("navbar--remove-padding");

      /* Show close-icon on the navbar */
      let close_icon = document.querySelector(".menu-icon");
      close_icon.classList.toggle ("menu-icon--toggle")

      /* Disappear menu-icon on the navbar*/
      let menu_icon = document.querySelector(".close-icon")
      menu_icon.classList.toggle("close-icon--toggle")
    }
  </script>
  </body>
</html>